name: "Auto Assign Reviewer"

on:
  pull_request:
    types: [opened, ready_for_review]
  issues:
    types: [opened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-reviewer:
    name: "Add Reviewer"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Auto Assign Reviewer and Assignee"
        uses: kentaro-m/auto-assign-action@v2.0.0